version: '2'
services:
  dv-hw2:
    image: python:3.3-alpine
    container_name: dv-hw2
    ports:
      - "8080:8080"
      - "2024:22"
    volumes:
      - .:/var/www
    restart: always
    working_dir: /var/www
    entrypoint: python -m http.server 8080